import { lazy } from 'react'
import {
  Eraser, Minimize2, Scaling, RefreshCw,
  Combine, Scissors, FileDown,
  QrCode, Palette, Braces, Binary, Type,
  AudioLines, MonitorPlay,
  Calculator, Quote, Timer, Layers, CalendarRange,
  LayoutGrid, Hash, Signature,
  Contact, ScanLine, LayoutDashboard,
  Volume2, GitCompare, Sparkles,
  Mic, Clapperboard, ScanText, PenLine,
} from 'lucide-react'

export const categories = [
  { id: 'study', name: 'Study', color: 'var(--cat-study)', title: ['Study', 'kit'], blurb: 'For grades, citations, focus and reviewing.' },
  { id: 'pdf', name: 'PDF', color: 'var(--cat-pdf)', title: ['PDF', 'essentials'], blurb: 'For readings, requirements and submissions.' },
  { id: 'image', name: 'Image', color: 'var(--cat-image)', title: ['Image', 'fixes'], blurb: 'For slides, posters and profile photos.' },
  { id: 'text', name: 'Writing & Code', color: 'var(--cat-text)', title: ['Writing', '& code'], blurb: 'For essays, org pubmats and programming classes.' },
  { id: 'media', name: 'Media', color: 'var(--cat-media)', title: ['Video', '& audio'], blurb: 'For reports, recorded presentations and projects.' },
]

export const tools = [
  // Study
  { id: 'gwa-calculator', category: 'study', name: 'GWA Calculator', icon: Calculator,
    description: 'Compute your GWA or QPI, check honors, and see the grades you need to hit a target.', uses: ['Dean\'s list', 'Latin honors', 'Scholarships'],
    keywords: 'gwa gpa qpi grade average calculator honors cum laude dean lister units',
    component: lazy(() => import('./study/GwaCalculator.jsx')) },
  { id: 'citation-generator', category: 'study', name: 'Citation Generator', icon: Quote,
    description: 'APA 7, MLA 9 and Chicago citations for websites, books and journals, plus a sorted reference list.', uses: ['Research papers', 'Thesis', 'Essays'],
    keywords: 'citation apa mla chicago reference bibliography works cited cite source',
    component: lazy(() => import('./study/CitationGenerator.jsx')) },
  { id: 'pomodoro', category: 'study', name: 'Pomodoro Timer', icon: Timer,
    description: 'Focus sprints and breaks with a chime, auto-start and a daily session count.', uses: ['Exam week', 'Deep work', 'Group study'],
    keywords: 'pomodoro timer focus study break productivity',
    component: lazy(() => import('./study/Pomodoro.jsx')) },
  { id: 'flashcards', category: 'study', name: 'Flashcards', icon: Layers,
    description: 'Paste your notes, then flip, shuffle and track what you already know.', uses: ['Quizzes', 'Board exams', 'Vocabulary'],
    keywords: 'flashcards flash cards review memorize quizlet study deck',
    component: lazy(() => import('./study/Flashcards.jsx')) },
  { id: 'schedule-maker', category: 'study', name: 'Class Schedule Maker', icon: CalendarRange,
    description: 'Build your weekly timetable, catch conflicts, and export it as a phone wallpaper.', uses: ['Enrollment', 'Wallpaper', 'Planning'],
    keywords: 'class schedule timetable maker wallpaper enrollment weekly',
    component: lazy(() => import('./study/ScheduleMaker.jsx')) },
  // Image
  { id: 'remove-background', category: 'image', name: 'Background Remover', icon: Eraser,
    description: 'Cut the background out of any photo, leaving a clean transparent PNG.', uses: ['ID photos', 'Pubmats', 'Slides'],
    keywords: 'remove bg cutout transparent png',
    component: lazy(() => import('./image/BackgroundRemover.jsx')) },
  { id: 'compress-image', category: 'image', name: 'Image Compressor', icon: Minimize2,
    description: 'Shrink photos so they fit upload limits, with no visible loss.', uses: ['LMS uploads', 'Email limits', 'Forms'],
    keywords: 'compress reduce size optimize tinypng',
    component: lazy(() => import('./image/ImageCompressor.jsx')) },
  { id: 'resize-image', category: 'image', name: 'Image Resizer', icon: Scaling,
    description: 'Resize to exact pixels or a percentage, with the aspect ratio kept.', uses: ['2x2 photos', 'Profile pics', 'Banners'],
    keywords: 'resize scale dimensions width height',
    component: lazy(() => import('./image/ImageResizer.jsx')) },
  { id: 'file-converter', category: 'image', name: 'File Type Converter', icon: RefreshCw,
    description: 'Pick what you have and what you need: PNG, JPG, WebP, PDF, or video to GIF.', uses: ['Portal uploads', 'Slides', 'Submissions'],
    keywords: 'convert converter file type format png jpg jpeg webp pdf images to pdf pdf to jpg video to gif mp4 animated',
    component: lazy(() => import('./image/FileConverter.jsx')) },

  { id: 'id-photo', category: 'image', name: 'ID Photo Maker', icon: Contact,
    description: 'Crop 2×2, 1×1 or passport photos with a face guide and print a full sheet.', uses: ['School ID', 'Passport', 'Requirements'],
    keywords: '2x2 1x1 id photo passport picture crop print sheet',
    component: lazy(() => import('./image/IdPhoto.jsx')) },
  { id: 'scan-cleaner', category: 'image', name: 'Scan Cleaner', icon: ScanLine,
    description: 'Straighten phone photos of paper, whiten the page and save a clean PDF.', uses: ['Worksheets', 'Handwritten work', 'Forms'],
    keywords: 'scan scanner camscanner document cleaner straighten perspective whiten photo of paper',
    component: lazy(() => import('./image/ScanCleaner.jsx')) },
  { id: 'collage', category: 'image', name: 'Collage Maker', icon: LayoutDashboard,
    description: 'Put 2–9 photos into a clean grid for posts and recaps.', uses: ['Org posts', 'Event recaps', 'Portfolios'],
    keywords: 'collage grid photo layout combine pictures instagram',
    component: lazy(() => import('./image/CollageMaker.jsx')) },

  // PDF
  { id: 'merge-pdf', category: 'pdf', name: 'Merge PDF', icon: Combine,
    description: 'Combine several PDFs into one file, in the order you choose.', uses: ['Readings', 'Requirements', 'Portfolios'],
    keywords: 'merge combine join pdf',
    component: lazy(() => import('./pdf/MergePdf.jsx')) },
  { id: 'split-pdf', category: 'pdf', name: 'Split PDF', icon: Scissors,
    description: 'Pull out just the pages you need, or split every page apart.', uses: ['Chapters', 'Exam reviewers', 'Forms'],
    keywords: 'split extract pages pdf',
    component: lazy(() => import('./pdf/SplitPdf.jsx')) },
  { id: 'compress-pdf', category: 'pdf', name: 'Compress PDF', icon: FileDown,
    description: 'Make scanned or photo-heavy PDFs small enough to submit.', uses: ['Scanned homework', '25 MB limits'],
    keywords: 'compress reduce shrink pdf size',
    component: lazy(() => import('./pdf/CompressPdf.jsx')) },

  { id: 'organize-pdf', category: 'pdf', name: 'Organize PDF', icon: LayoutGrid,
    description: 'Rotate, delete and drag pages into order, or combine pages from several PDFs.', uses: ['Sideways scans', 'Blank pages', 'Reordering'],
    keywords: 'organize rotate delete reorder rearrange pages pdf',
    component: lazy(() => import('./pdf/OrganizePdf.jsx')) },
  { id: 'number-pdf', category: 'pdf', name: 'Page Numbers & Watermark', icon: Hash,
    description: 'Stamp page numbers or a DRAFT/CONFIDENTIAL watermark on every page.', uses: ['Thesis', 'Reports', 'Drafts'],
    keywords: 'page numbers numbering watermark stamp draft confidential pdf',
    component: lazy(() => import('./pdf/NumberPdf.jsx')) },
  { id: 'sign-pdf', category: 'pdf', name: 'Sign PDF', icon: Signature,
    description: 'Draw, type or upload your signature and place it on any page.', uses: ['Waivers', 'Consent forms', 'Clearances'],
    keywords: 'sign signature pdf esign fill form waiver',
    component: lazy(() => import('./pdf/SignPdf.jsx')) },

  // Text & Dev
  { id: 'qr-code', category: 'text', name: 'QR Code Generator', icon: QrCode,
    description: 'QR codes for links, Wi-Fi or contacts, saved as PNG or SVG.', uses: ['Org posters', 'Sign-up forms', 'Booths'],
    keywords: 'qr code generator wifi link',
    component: lazy(() => import('./text/QrGenerator.jsx')) },
  { id: 'color-palette', category: 'text', name: 'Color Palette', icon: Palette,
    description: 'Generate color palettes that match, then copy the hex codes.', uses: ['Slides', 'Pubmats', 'UI projects'],
    keywords: 'color palette hex coolors generator',
    component: lazy(() => import('./text/ColorPalette.jsx')) },
  { id: 'json-formatter', category: 'text', name: 'JSON Formatter', icon: Braces,
    description: 'Prettify, minify and validate JSON, and see exactly where it breaks.', uses: ['CS classes', 'APIs', 'Debugging'],
    keywords: 'json format prettify minify validate beautify',
    component: lazy(() => import('./text/JsonFormatter.jsx')) },
  { id: 'base64', category: 'text', name: 'Base64 Encoder', icon: Binary,
    description: 'Encode or decode Base64 for text and files.', uses: ['Web dev', 'Data URLs'],
    keywords: 'base64 encode decode',
    component: lazy(() => import('./text/Base64Tool.jsx')) },
  { id: 'word-counter', category: 'text', name: 'Word Counter', icon: Type,
    description: 'Words, characters, sentences and reading time, as you type.', uses: ['Essays', 'Abstracts', 'Speeches'],
    keywords: 'word count character counter reading time case',
    component: lazy(() => import('./text/WordCounter.jsx')) },

  { id: 'read-aloud', category: 'text', name: 'Read Aloud', icon: Volume2,
    description: 'Listen to readings or proofread your essay by ear, with the current sentence highlighted.', uses: ['Proofreading', 'Readings', 'Speeches'],
    keywords: 'text to speech tts read aloud listen voice',
    component: lazy(() => import('./text/ReadAloud.jsx')) },
  { id: 'diff-checker', category: 'text', name: 'Compare Drafts', icon: GitCompare,
    description: 'See exactly what changed between two versions of your text.', uses: ['Revisions', 'Group edits', 'Code'],
    keywords: 'diff compare text difference checker drafts changes',
    component: lazy(() => import('./text/DiffChecker.jsx')) },
  { id: 'text-cleaner', category: 'text', name: 'Text Cleaner', icon: Sparkles,
    description: 'Fix broken line breaks from PDFs, extra spaces, bullets and letter case.', uses: ['PDF quotes', 'Notes', 'Formatting'],
    keywords: 'clean text remove line breaks spaces pdf copy paste format case converter',
    component: lazy(() => import('./text/TextCleaner.jsx')) },

  { id: 'ai-detector', category: 'text', name: 'AI Detector', icon: ScanText,
    description: 'Check whether text reads as AI-written, and see the exact phrases that make it sound that way. Runs on your device.', uses: ['Self-checks', 'Revising', 'Group work'],
    keywords: 'ai detector detection chatgpt gpt written generated checker gptzero turnitin phrases highlight delve robotic writing tells',
    component: lazy(() => import('./text/AiDetector.jsx')) },
  { id: 'rephraser', category: 'text', name: 'Rephraser', icon: PenLine,
    description: 'Say it differently: clearer, simpler, more formal or shorter. Runs on your device.', uses: ['Awkward sentences', 'Emails', 'Summaries'],
    keywords: 'rephrase paraphrase reword rewrite paraphraser quillbot sentence simplify formal shorten',
    component: lazy(() => import('./text/Rephraser.jsx')) },

  // Media
  { id: 'audio-trimmer', category: 'media', name: 'Audio Trimmer', icon: AudioLines,
    description: 'Cut the part of a recording you need, with fades.', uses: ['Interviews', 'Podcasts', 'Intros'],
    keywords: 'audio trim cut mp3 wav ringtone',
    component: lazy(() => import('./media/AudioTrimmer.jsx')) },
  { id: 'screen-recorder', category: 'media', name: 'Screen Recorder', icon: MonitorPlay,
    description: 'Record your screen, a window or a tab, with your voice.', uses: ['Recorded reports', 'Tutorials', 'Demos'],
    keywords: 'screen record capture video',
    component: lazy(() => import('./media/ScreenRecorder.jsx')) },
  { id: 'voice-recorder', category: 'media', name: 'Voice Recorder', icon: Mic,
    description: 'Record voice notes, recitations and interviews, and save them as audio files.', uses: ['Recitations', 'Interviews', 'Voice notes'],
    keywords: 'voice recorder audio record microphone mic',
    component: lazy(() => import('./media/VoiceRecorder.jsx')) },
  { id: 'video-compressor', category: 'media', name: 'Video Compressor', icon: Clapperboard,
    description: 'Shrink a video to a target size so it fits upload limits.', uses: ['LMS uploads', 'Messenger', 'Email'],
    keywords: 'video compress reduce size shrink mp4 upload limit',
    component: lazy(() => import('./media/VideoCompressor.jsx')) },
]

export const categoryById = Object.fromEntries(categories.map((c) => [c.id, c]))
export const toolById = Object.fromEntries(tools.map((t) => [t.id, t]))

/** Tools merged into other tools; old links open the tool that replaced them. */
export const legacyTools = {
  'convert-image': '/tools/file-converter?from=jpg&to=png',
  'images-to-pdf': '/tools/file-converter?from=jpg&to=pdf',
  'pdf-to-images': '/tools/file-converter?from=pdf&to=png',
  'video-to-gif': '/tools/file-converter?from=video&to=gif',
  'ai-phrase-highlighter': '/tools/ai-detector',
}

/** Common school jobs, shown as shortcuts on the home page. */
export const studentTasks = [
  { label: 'Compute my GWA', tool: 'gwa-calculator' },
  { label: 'Cite a source in APA', tool: 'citation-generator' },
  { label: 'Scan my worksheet', tool: 'scan-cleaner' },
  { label: 'Make a 2×2 ID photo', tool: 'id-photo' },
  { label: 'Shrink a PDF for the LMS', tool: 'compress-pdf' },
  { label: 'Sign a waiver', tool: 'sign-pdf' },
  { label: 'Start a study timer', tool: 'pomodoro' },
  { label: 'Combine readings', tool: 'merge-pdf' },
]
